name: Checkout Repository

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkout:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
